# ===========
# LEGACY UNUSED CODE
# ===========
#
# In order to cope with the lack of a 'publisher' filter, the query was enriched by using DOI stems for Springer Nature. This was fixed on February 11, 2019.
#
# The list below could become handy in other situations.
#

DOI_STEMS = {
    '10.1013':
    'Nature Publishing Group',
    '10.1038':
    'Nature Publishing Group',
    '10.1057':
    'Nature Publishing Group - Macmillan Publishers',
    '10.1251':
    'Springer (Biological Procedures Online)',
    '10.1186':
    'Springer (Biomed Central Ltd.)',
    '10.4076':
    'Springer (Cases Network, Ltd.)',
    '10.1114':
    'Springer (Kluwer Academic Publishers - Biomedical Engineering Society',
    '10.1023':
    'Springer (Kluwer Academic Publishers)',
    '10.5819':
    'Springer - (backfiles)',
    '10.1361':
    'Springer - ASM International',
    '10.1379':
    'Springer - Cell Stress Society International',
    '10.1065':
    'Springer - Ecomed Publishers',
    '10.1381':
    'Springer - FD Communications',
    '10.7603':
    'Springer - Global Science Journals',
    '10.1385':
    'Springer - Humana Press',
    '10.4098':
    'Springer - Mammal Research Institute',
    '10.3758':
    'Springer - Psychonomic Society',
    '10.1617':
    'Springer - RILEM Publishing',
    '10.5052':
    'Springer - Real Academia de Ciencias Exactas, Fisicas y Naturales',
    '10.1245':
    'Springer - Society of Surgical Oncology',
    '10.4333':
    'Springer - The Korean Society of Pharmaceutical Sciences and Technology',
    '10.1365':
    'Springer Fachmedien Wiesbaden GmbH',
    '10.1891':
    'Springer Publishing Company',
    '10.1140':
    'Springer-Verlag',
    '10.1007':
    'Springer-Verlag',
}

RESTRICT_CLAUSE = "AND (%s) " % " OR ".join(["doi:%s*" % x for x in DOI_STEMS])
# => AND (doi:10.1038* OR doi:10.1007* OR doi:10.1186*)



# obtained from https://github.com/markmarkoh/datamaps
# used to fake links to the map
COUNTRIES_LIST = ['Afghanistan',
 'Angola',
 'Albania',
 'United Arab Emirates',
 'Argentina',
 'Armenia',
 'Antarctica',
 'French Southern and Antarctic Lands',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Burundi',
 'Belgium',
 'Benin',
 'Burkina Faso',
 'Bangladesh',
 'Bulgaria',
 'The Bahamas',
 'Bosnia and Herzegovina',
 'Belarus',
 'Belize',
 'Bolivia',
 'Brazil',
 'Brunei',
 'Bhutan',
 'Botswana',
 'Central African Republic',
 'Canada',
 'Switzerland',
 'Chile',
 'China',
 'Ivory Coast',
 'Cameroon',
 'Democratic Republic of the Congo',
 'Republic of the Congo',
 'Colombia',
 'Costa Rica',
 'Cuba',
 'Northern Cyprus',
 'Cyprus',
 'Czech Republic',
 'Germany',
 'Djibouti',
 'Denmark',
 'Dominican Republic',
 'Algeria',
 'Ecuador',
 'Egypt',
 'Eritrea',
 'Spain',
 'Estonia',
 'Ethiopia',
 'Finland',
 'Fiji',
 'Falkland Islands',
 'France',
 'French Guiana',
 'Gabon',
 'United Kingdom',
 'Georgia',
 'Ghana',
 'Guinea',
 'Gambia',
 'Guinea Bissau',
 'Equatorial Guinea',
 'Greece',
 'Greenland',
 'Guatemala',
 'Guyana',
 'Honduras',
 'Croatia',
 'Haiti',
 'Hungary',
 'Indonesia',
 'India',
 'Ireland',
 'Iran',
 'Iraq',
 'Iceland',
 'Israel',
 'Italy',
 'Jamaica',
 'Jordan',
 'Japan',
 'Kazakhstan',
 'Kenya',
 'Kyrgyzstan',
 'Cambodia',
 'South Korea',
 'Kosovo',
 'Kuwait',
 'Laos',
 'Lebanon',
 'Liberia',
 'Libya',
 'Sri Lanka',
 'Lesotho',
 'Lithuania',
 'Luxembourg',
 'Latvia',
 'Morocco',
 'Moldova',
 'Madagascar',
 'Mexico',
 'Macedonia',
 'Mali',
 'Myanmar',
 'Montenegro',
 'Mongolia',
 'Mozambique',
 'Mauritania',
 'Malawi',
 'Malaysia',
 'Namibia',
 'New Caledonia',
 'Niger',
 'Nigeria',
 'Nicaragua',
 'Netherlands',
 'Norway',
 'Nepal',
 'New Zealand',
 'Oman',
 'Pakistan',
 'Panama',
 'Peru',
 'Philippines',
 'Papua New Guinea',
 'Poland',
 'Puerto Rico',
 'North Korea',
 'Portugal',
 'Paraguay',
 'Qatar',
 'Romania',
 'Russia',
 'Rwanda',
 'Western Sahara',
 'Saudi Arabia',
 'Sudan',
 'South Sudan',
 'Senegal',
 'Solomon Islands',
 'Sierra Leone',
 'El Salvador',
 'Somaliland',
 'Somalia',
 'Republic of Serbia',
 'Suriname',
 'Slovakia',
 'Slovenia',
 'Sweden',
 'Swaziland',
 'Syria',
 'Chad',
 'Togo',
 'Thailand',
 'Tajikistan',
 'Turkmenistan',
 'East Timor',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Taiwan',
 'United Republic of Tanzania',
 'Uganda',
 'Ukraine',
 'Uruguay',
 'United States of America',
 'Uzbekistan',
 'Venezuela',
 'Vietnam',
 'Vanuatu',
 'West Bank',
 'Yemen',
 'South Africa',
 'Zambia',
 'Zimbabwe']